travis:
  secure:
    BINSTAR_TOKEN: hFEA15C0BVNWqEllw/JhM3RcZ641R5rq8gv+3rI4G2WcNH11tkC5YbAEW5bOfPxuXWjAcE6pFg96+BWQ+QExA5Ls4x3ctBHN99f+kxtfeKbMcEXgpxdp4lpZp0oNl8M1E5B3/BDmxb/eCPe8169hmOpuh4ag3uQYz67H89+9fXu+GqOeHHprbBUBOwk010IOdrz5A/Mg1P2ribI1UexaVZoDgK729ku7DVsi2zgQLwDaNzw9koD+6Dauh8jh4y5KovdPrZdUmu8DC7SMNiIg0IoEg2BJu9mEvnGb51lS2TM5uKzTCwDsOHJTbUY8tRWvjdXzvDE20cdjBjHY/0wrD3XJwAuMyn97/yyDtvVmRE4k5qQ5pWV7ijUWBlS/fK5nlpGXksF4RkaLNbLiuakfNBRd94Kw4/TCH8dMRxj9iAxZK5X6b4FpqZHMmNHMjsbSHvgUb7qhVrPXRnajdBNRYDoOMXvt8UTMoWyLgTSTfpAJO3tb76P+dikL8ZjyJKI+VNr6eOWij33KQHu1+8xXXp5+DxnSBWsKg++Boq9dn79ptR94dSvg+u+pbR+JUmDIhw7fsHSOyBf1ou53UjRDQIokY7MoCrX+gxz1RpEiVNDO4dWlutyu2k8q/85TAVcuyXHXqkyeQXFiAYIfhjnLB/pEwCSnwF+qVtXvVRrFeP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
